### ISSUE TITLE
sspak Refactor

### ISSUE THREAD

**Issue by JZubero** [Level51/silverstripe-backuper#3]
The current version (0.1.1) uses the module ifsnop/mysqldump-php for creating a db dump and packing it along with the assets dir to a zip archive (FlxZipArchive.php).

We want to switch to the SSPak approach:
- http://silverstripe.github.io/sspak/
- https://github.com/silverstripe/sspak

The module needs [some commands](https://github.com/silverstripe/sspak#how-it-works) to be available on the system. For this we need some logic that checks the availability of the commands/binaries with an info in the SilverStripe BE.

**Comment by FabianGoettl** [comment]
Implemented sspak by direct PHP access instead of command line execution. No sspak installation in /bin required.
